name: Tests

on:
  push:
    branches: [ "aperture" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "aperture" ]

# Builds images for target boards.
permissions:
  contents: read

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [21.x]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Node.JS ${{ matrix.node }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Yarn install
        run: yarn install
      # - name: Depcheck
      #   run: yarn run deps
      - name: Build Javascript
        run: yarn run build
      - name: Test Js
        run: yarn run test
      - name: Lint Javascript
        run: yarn run lint
